spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    template:
      exchange: data-exchange
  application:
    name: user-service
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import: optional:configserver:http://localhost:8888
server:
  port: 8081

