server:
  port: 8082
spring:
  application:
    name: auth-service
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
jwt:
  secret-key: VGhpc1NIaXRJc1RoZVNjcmV0S2V5Rm9yV2hhdGV2ZXI=
  expiration-time: 864_000_000


logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.atlas: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n"

